# -*- coding: utf-8 -*-
"""Exercícios iniciais.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UC77jKy0CzVEuXT4pmtTMi-yTXW6FCjl
"""

import numpy as np
import math as m

# Exercício 1

A = int(input("Insira o valor de A: "))
B = int(input("Insira o valor de B: "))

X = A + B

print("X =", X)

# Exercício 2

R = float(input("Insira o valor do raio: "))

pi = 3.14159
A = pi*(R**2)

print( "A = %0.4f" %A)

# Exercício 3

A = float(input("Insira o valor de A: "))
B = float(input("Insira o valor de B: "))
C = float(input("Insira o valor de C: "))

M = (A*2 + B*3 + C*5)/10

print( "MEDIA = %0.1f" %M)

# Exercício 4

A = float(input("Insira o valor de A: "))
B = float(input("Insira o valor de B: "))
C = float(input("Insira o valor de C: "))

pi = 3.14159
Ti = A*C/2
Ci  = pi*C**2
Ta = (A + B)*C/2
Q  = B**2
R  = A*B

print( "\nTRIANGULO = %0.3f" %Ti,
       "\nCIRCULO = %.3f" %Ci,
       "\nTRAPEZIO = %.3f" %Ta,
       "\nQUADRADO = %.3f" %Q,
       "\nRETANGULO = %.3f" %R)

# Exercício 5

print("Abaixo, digite os pontos x e y, colocando um espaço entre eles, como segue o exemplo - x y: 1.2 3.4\n")
x1 , y1 = [float(i) for i in input("x1 y1: ").split()]
x2 , y2 = [float(i) for i in input("x2 y2: ").split()]

d = m.sqrt((x2-x1)**2 + (y2-y1)**2)

print("\nA distância entre os pontos vale: %.4f" %d)

# Exercício 6

N = int(input("Insira o número do funcionário: "))
H = int(input("Insira o número de horas trabalhadas: "))
V = float(input("Insira o valor da hora trabalhada: "))

S = H*V

print("\nNUMBER =", N,
      "\nSALARY = U$ %.2f" %S)

# Exercício 7

x = int(input("Insira a idade em dias: "))

A = x//365
M = (x - A*365)//30
D = x - A*365 - M*30

print("\n%i ano(s)" %A,
      "\n%i mes(es)" %M,
      "\n%i dia(s)" %D)

# Exercício 8

a = float(input("Insira o valor de a: "))
b = float(input("Insira o valor de b: "))
c = float(input("Insira o valor de c: "))

n = b**2 - 4*a*c

if a == 0:
  print("\nImpossível calcular")

else:
  if n < 0:
    print("\nEssa equação não possui raízes reais.")

  elif n == 0:
    x = -b/(2*a)
    print("\nAs raízes são iguais e seu valor é: %.5f" %x)

  elif n > 0:
    x1 = (-b + m.sqrt(n))/(2*a)
    x2 = (-b - m.sqrt(n))/(2*a)
    print("\nR1 = %.5f" %x1,
          "\nR2 = %.5f" %x2)

# Exercício 9

x = int(input("Insira o DDD: "))

n = 0

DDD    = [        61,        71,         11,              21,            32,        19,       27,              31,           55]
Estado = ["Brasília","Salvador","São Paulo","Rio de Janeiro","Juiz de Fora","Campinas","Vitória","Belo Horizonte","Santa Maria"]

if x in DDD:
  for i in DDD:
    if x == DDD[n]:
      print("\n%s" %Estado[n])
    n += 1
else:
  print("\nDDD não cadastrado")

# Exercício 10

x = 1
n = 0
Vi = 0
Vg = 0
E = 0

while x == 1:

  Gi = int(input("Número de gols marcados pelo Inter no último GRENAL: "))
  Gg = int(input("Número de gols marcados pelo Grêmio no último GRENAL: "))

  if Gi > Gg:
    Vi += 1
  elif Gg > Gi:
    Vg += 1
  elif Gg == Gi:
    E += 1

  n += 1

  x = int(input("Novo grenal (1-sim 2-nao)\n"))

  if x != 1:

    if Vi > Vg:
      V = "O time que mais venceu GRENAIS foi o Inter"
    elif Vg > Vi:
      V = "O time que mais venceu GRENAIS foi o Grêmio"
    elif Vg == Vi:
      V = "Não houve vencedor"
      
    print("\nNúmero de GRENAIS computados: %i" %n,
          "\nNúmero de vitórias do Inter: %i" %Vi,
          "\nNúmero de vitórias do Grêmio: %i" %Vg,
          "\nNúmero de empates: %i" %E,
          "\n%s" %V)

# Exercício 11

print("Abaixo, digite a altura do pulo do sapo (1<=P<=5) e o número de canos (2<=N<=100), respectivamente, colocando um espaço entre eles, como segue o exemplo - P N: 2 4\n")
P , N = [int(i) for i in input("P N: ").split()]

Error = False

if P < 1 or P > 5:
  Error = True
  print("Altura do pulo do sapo inválida.")
if N < 2 or N > 100:
  Error = True
  print("Número de canos inválido.")

if Error == False:
  print("\nAgora, digite os números (0<H<=10) que definirão a altura dos %i canos, colocando um espaço entre cada número, como segue o exemplo - H : 1 3 5 3\n")
  H = [int(i) for i in input("H: ").split()]

NH = int(len(H))

for i in H:
  if i <= 0 or i > 10:
    Error = True
    print("Altura do cano inválida.")
if NH != N:
  Error = True
  print("Número de alturas para os canos, {}, em desacordo com o número de canos, {}.".format(NH, N))

j = 0
k = 1
Lost = False

if Error == False:
  while k < len(H):
    if abs(H[k]-H[j]) > P:
      Lost = True
    j += 1
    k += 1

  if Lost == False:
    print("\nYOU WIN")
  else:
    print("\nGAME OVER")

# Exercício 12

T = int(input("Insira o tipo de chá (1<=T<=4): "))

print("\nAbaixo, digite as respostas dadas pelos cinco participantes, colocando um espaço entre elas, como segue o exemplo - A B C D E: 1 2 3 2 1\n")
P = [int(i) for i in input("A B C D E: ").split()]

n = 0
j = 0

for i in P:
  if T == P[j]:
    n += 1
  j += 1
    
print("\n{}".format(n))

# Exercício 13

N = int(input("Insira o número (1<N<=100) de medidas de paisagens: "))

Error = False

if N <= 1 or N > 100:
  Error = True
  print("Número de medidas inválido")

print("\nAbaixo, digite os números (-10000<=Hi<=10000 | 1<=i<=N) que definirão a altura das {} medidas, colocando um espaço entre cada número, como segue o exemplo - H : 1 4 -2\n".format(N))
Hi = [int(i) for i in input("Hi: ").split()]

for i in Hi:
  if i <= -10000 or i > 10000:
    Error = True
    print("Valor para altura das medidas inválido.")
if N != int(len(Hi)):
  Error = True
  print("Número de medidas da paisagem, {}, em desacordo com o número alturas, {}.".format(N, len(Hi)))


j = 0
k = 1
l = 2

if Error == False:
  while l < len(Hi):
    if Hi[k]-Hi[j] > 0:
      if Hi[l]-Hi[k] > 0:
        Error = True
    else:
      if Hi[l]-Hi[k] < 0:
        Error = True

    j += 1
    k += 1
    l += 1

if Error == False:
  print("\n1")
else:
  print("\n0")

# Exercício 14

N = int(input("Insira o número de jogadores (1<=N<=105) que haverá no seu time: "))

Error = False

if N < 1 or N > 105:
  Error = True
  print("\nNúmero de alunos inválido.")

if Error == False:
  print("\nAgora, insira o voto (vi = 0 ou 1, desfavorável ou favorável, respectivamente) de cada um dos jogadores, colocando um espaço entre cada número, como segue o exemplo - vi : 1 3 5 3\n")
  vi = [int(i) for i in input("vi: ").split()]

Nvi = int(len(vi))

for i in vi:
  if i != 0 and i != 1:
    Error = True
    print("\nNúmero inválido para o voto.")
if Nvi != N:
  Error = True
  print("\nNúmero de votos, {}, em desacordo com o número de jogadores, {}.".format(Nvi, N))

v1 = vi.count(1)

if Error == False:
  if v1 >= (N*2/3):
    print("\nimpeachment")
  else:
    print("\nacusacao arquivada")

# Exercício 15

SoaD = ["PROXYCITY","P.Y.N.G","DNSUEY!","SERVERS","HOST!","CRIPTONIZE","OFFLINE DAY","SALT","ANSWER!","RAR?","WIFI ANTENNAS"]

C = int(input("Insira o número de casos de teste: "))

Error = False

if C < 1:
  Error = True
  print("\nNúmero de casos de teste inválido.")

if Error == False:
  print("\nAbaixo, digite os valores para dois números inteiros (0<=X,Y<=5), colocando um espaço entre eles, como segue o exemplo - X Y: 1 2")

  for i in range(C):
    X , Y = [int(i) for i in input("\nX Y: ").split()]

    if X < 0 or X > 5:
      Error = True
      print("Valor inválido para X.")
    elif Y < 0 or Y > 5:
      Error = True
      print("Valor inválido para Y.")

    if Error == False:
      print(SoaD[X+Y])
    else:
      Error = False

# Exercício 16

print("\nAbaixo, insira o número de competidores, a quantidade de folhas de papel especial compradas pela Diretora e a quantidade de folhas de papel especial que cada compedidor deve receber (1<=C,P,F<=1000), respectivamente, colocando um espaço entre eles, como segue o exemplo - C P F: 10 100 10")
C , P , F = [int(i) for i in input("\nC P F: ").split()]

Error = False

if C < 1 or C > 1000:
  Error = True
  print("\nValor inválido para C.")
elif P < 1 or P > 1000:
  Error = True
  print("\nValor inválido para P.")
elif F < 1 or F > 1000:
  Error = True
  print("\nValor inválido para F.")

if Error == False:
  if P >= C*F:
    print("\nS")
  else:
    print("\nN")

# Exercício 17

print("\nAbaixo, insira a escolha do jogador 1 (0=ímpar,1=par), o número escolhido pelos jogadores 1 e 2 (1<=j1,j2<=100), se o jogador 1 roubou (0=não,1=sim) e se o jogador 2 acusou o jogador 1 de roubo (0=não,1=sim), respectivamente, colocando um espaço entre eles, como segue o exemplo - p j1 j2 r a: 1 4 5 0 0")
p , j1 , j2 , r , a = [int(i) for i in input("\np j1 j2 r a: ").split()]

Error = False

if p != 0 and p != 1:
  Error = True
  print("\nValor inválido para p.")
elif j1 < 1 or j1 > 100:
  Error = True
  print("\nValor inválido para j1.")
elif j2 < 1 or j2 > 100:
  Error = True
  print("\nValor inválido para j2.")
elif r != 0 and r != 1:
  Error = True
  print("\nValor inválido para r.")
elif a != 0 and a != 1:
  Error = True
  print("\nValor inválido para a.")

n = (j1 + j2) % 2
v = 0

if Error == False:
  if p == 0:           # j1 escolheu ímpar
    if n == 0:           # soma deu par
      if r == 0:           # j1 não roubou
        if a == 0:           # j2 não acusou
          v = 2
        else:                # j2 acusou
          v = 1
      else:                # j1 roubou
        if a == 0:           # j2 não acusou
          v = 1
        else:                # j2 acusou
          v = 2
    else:                # soma deu ímpar
      if r == 0:           # j1 não roubou
        if a == 0:           # j2 não acusou
          v = 1
        else:                # j2 acusou
          v = 1
      else:                # j1 roubou
        if a == 0:           # j2 não acusou
          v = 1
        else:                # j2 acusou
          v = 2
  else:                # j1 escolheu par
    if n == 0:           # soma deu par
      if r == 0:           # j1 não roubou
        if a == 0:           # j2 não acusou
          v = 1
        else:                # j2 acusou
          v = 1
      else:                # j1 roubou
        if a == 0:           # j2 não acusou
          v = 1
        else:                # j2 acusou
          v = 2
    else:                # soma deu ímpar
      if r == 0:           # j1 não roubou
        if a == 0:           # j2 não acusou
          v = 2
        else:                # j2 acusou
          v = 1
      else:                # j1 roubou
        if a == 0:           # j2 não acusou
          v = 1
        else:                # j2 acusou
          v = 2

  if v == 1:
    print("\nJogador 1 ganha!")
  elif v == 2:
    print("\nJogador 2 ganha!")

# Exercício 18

B = int(input("Insira a quantidade de bolinhas que Amélia já possui (B>1): "))

Error = False

if Error == False:

  if B <= 0:
    Error = True
    print("\nValor inválido para B.")

  G = float(input("\nInsira a quantidade de galhos de sua nova árvore de natal (100<G<1000): "))

  if G <= 100 or G >= 1000:
    Error = True
    print("\nValor inválido para G.")

  x = m.floor((G/2)-B)

  if x > 0:
    print("\nFaltam {} bolinha(s)" .format(x))
  elif x <= 0:
    print("\nAmelia tem todas bolinahs!")

# Exercício 19

C = int(input("Insira o número de casos de teste: "))

Error = False

if C < 1:
  Error = True
  print("\nNúmero de casos de teste inválido.")

if Error == False:
  print("\nAbaixo, digite os valores para dois números inteiros (1<=N,M<=100), colocando um espaço entre eles, como segue o exemplo - N M: 2 10")

  for i in range(C):
    N , M = input("\nN M: ").split()

    if int(N) < 1 or int(N) > 100:
      Error = True
      print("\nValor inválido para N.")
      break
    elif int(M) < 1 or int(M) > 100:
      Error = True
      print("\nValor inválido para M.")
      break

    print("\nO número de dígitos de NM é: {}" .format(len(N+M)))

    N = int(N)
    M = int(M)

    print("\nO número de dígitos de N^M é: {}".format(len(str(N**M))))

# Exercício 20

D = int(input("Insira a distância entre o robô e início da quadra (0<=D<=2000), em centímetros, no momento do lançamento: "))

if D >= 0 and D <= 800:
  print("\n1")
elif D > 800 and D <= 1400:
  print("\n2")
elif D > 1400 and D <= 2000:
  print("\n3")
else:
  print("\nValor inválido para D.")

# Desafio

lista_1 = ['CCNE','CT','CTISM','CCS','CT','CAU']
lista_2 = ['CCSH','CAL','POLI','CCR','CEFD']

lista = lista_1 + lista_2

print(lista)

alfabetica = sorted(lista)

print("\n{}".format(alfabetica))

